added new parser names and in-depth docs
phac-nml/irida-uploader pull request #116
Opened 2021-07-23 22:15 UTC by JeffreyThiessen

## Description of changes
Changes:
* Added options for `miseq_win10_jun2021` and `seqfu` parsers (uses existing parsers)
* Added in-depth documentation on using the irida uploader with windows 10 updated miseqs

## Related issue
Fixes #115 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-07-26 20:54 UTC, tom114 requested changes
Thanks for the docs @JeffreyThiessen .  I just added some wording/formatting suggestions below.

2021-07-26 20:54 UTC, tom114 commented on docs/parsers/miseq_win10.md
> +2. **This is probably the most complicated way of creating a run in LRM and a majority of things can go wrong; we recommended against this way**. if a user uses IEM to create a sample sheet and modif
Do you want to flip this to the 3rd option since it's the least recommended?

2021-07-27 20:10 UTC, JeffreyThiessen commented on docs/parsers/miseq_win10.md
> +The upgrade to Windows 10 comes with v4.0 of MiSeq Control Software (MCS) and v3.0 of Local Run Manager (LRM). The upgrade of LRM to v3.0 that does not allow sample sheets created in IEM to be upload
I have updated all the text based on your suggestions. I agree that this improves readability by a lot.

2021-08-03 18:31 UTC, tom114 approved these changes

2021-08-03 19:43 UTC, merged